name: Docker Image CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKENSITO }}
    - name: Build, run and push Docker image
      run: |
           docker build . --tag ghcr.io/oscarabundez23/image-motor-estatico:latest
           docker run ghcr.io/oscarabundez23/image-motor-estatico:latest
           docker push ghcr.io/oscarabundez23/image-motor-estatico:latest
